site_name: Manual de Acessibilidade Digital
site_description: Guia de acessibilidade digital

theme:
  name: material
  language: pt
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top

  palette:
    - scheme: default
      primary: orange
      accent: deep orange
      toggle:
        icon: material/lightbulb
        name: Modo escuro
    #tema escuro
    - scheme: slate
      primary: orange
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Ativar modo claro

nav:
  - Início: index.md
  - Manual de Acessibilidade: 
    - Desenvolvimento Web: "manual/devWeb.md"
    - Design: "manual/design.md"
    - Geração de Conteúdo: "manual/geracaoCont.md"
    - Gestão de Projeto: "manual/gestaoProj.md"
  - Ferramentas: 
    - Antes de Começar: "ferramentas/introducao.md"
    - VLibras: "ferramentas/vLibras.md"
    - ASES: "ferramentas/ases.md"
    - Acess Monitor Plus: "ferramentas/acess.md"
    - WAVE: "ferramentas/wave.md"
  - Fontes: Recursos.md
  - Sobre: Sobre.md

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.emoji
  

extra_css:
- stylesheets/custom.css
- stylesheets/extra.css

extra_javascript:
  - js/graficos.js
  - js/grafico_p2.js
